# Generated by Django 4.1.2 on 2022-10-18 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('text', models.TextField(blank=True, verbose_name='Текст поста')),
                ('poster', models.ImageField(upload_to='blog/', verbose_name='Постер')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('tag', models.ManyToManyField(to='blog.tags', verbose_name='теги')),
            ],
        ),
    ]
