# Generated by Django 4.1.2 on 2022-10-20 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_like_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='picture',
            new_name='post',
        ),
    ]
